#!/usr/bin/env python3
"""
Helipad YOLO Training Script

Trains a YOLOv8n model to detect helipads from aerial drone footage.
Uses transfer learning with a frozen backbone for efficient training.

Usage:
    python train.py
    python train.py --epochs 100 --device cuda
    python train.py --freeze 10 --batch 16
"""

import os
import argparse
from pathlib import Path
from datetime import datetime


def create_dataset_yaml(dataset_path):
    """Create dataset.yaml configuration file."""
    yaml_content = f"""# Helipad Detection Dataset
# Auto-generated by train.py

path: {dataset_path.absolute()}
train: train/images
val: val/images

# Class names
names:
  0: helipad
"""
    yaml_path = dataset_path / 'dataset.yaml'
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)
    print(f"Created {yaml_path}")
    return yaml_path


def count_images(dataset_path):
    """Count training and validation images."""
    train_dir = dataset_path / 'train' / 'images'
    val_dir = dataset_path / 'val' / 'images'

    train_count = len(list(train_dir.glob('*.jpg'))) + len(list(train_dir.glob('*.png')))
    val_count = len(list(val_dir.glob('*.jpg'))) + len(list(val_dir.glob('*.png')))

    return train_count, val_count


def main():
    parser = argparse.ArgumentParser(description='Train helipad detection model')
    parser.add_argument('--dataset', type=str, default='dataset',
                        help='Dataset directory')
    parser.add_argument('--epochs', type=int, default=50,
                        help='Number of training epochs')
    parser.add_argument('--batch', type=int, default=16,
                        help='Batch size')
    parser.add_argument('--imgsz', type=int, default=320,
                        help='Image size for training')
    parser.add_argument('--device', type=str, default='mps',
                        help='Device: mps, cuda, or cpu')
    parser.add_argument('--freeze', type=int, default=10,
                        help='Number of layers to freeze (0=none, 10=backbone)')
    parser.add_argument('--model', type=str, default='yolov8n.pt',
                        help='Base model to fine-tune')
    parser.add_argument('--resume', type=str, default=None,
                        help='Resume from checkpoint')
    args = parser.parse_args()

    # Import here to show helpful error if not installed
    try:
        from ultralytics import YOLO
    except ImportError:
        print("Ultralytics not installed. Run: pip install -r requirements.txt")
        return

    dataset_path = Path(args.dataset)

    # Check dataset exists
    if not dataset_path.exists():
        print(f"Dataset directory not found: {dataset_path}")
        print("Run 'python augment.py' first to generate training data")
        return

    # Count images
    train_count, val_count = count_images(dataset_path)
    if train_count == 0:
        print("No training images found!")
        print("Run 'python augment.py' first to generate training data")
        return

    print(f"Dataset: {train_count} training, {val_count} validation images")

    # Create dataset.yaml
    yaml_path = create_dataset_yaml(dataset_path)

    # Load model
    if args.resume:
        print(f"Resuming from {args.resume}")
        model = YOLO(args.resume)
    else:
        print(f"Loading base model: {args.model}")
        model = YOLO(args.model)

    # Training configuration
    print(f"\nTraining Configuration:")
    print(f"  Epochs: {args.epochs}")
    print(f"  Batch size: {args.batch}")
    print(f"  Image size: {args.imgsz}")
    print(f"  Device: {args.device}")
    print(f"  Frozen layers: {args.freeze}")

    # Train
    print("\nStarting training...")
    results = model.train(
        data=str(yaml_path),
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        device=args.device,

        # Fine-tuning settings
        freeze=args.freeze,          # Freeze backbone layers
        lr0=0.001,                   # Lower learning rate for fine-tuning
        lrf=0.01,                    # Final learning rate ratio
        optimizer='AdamW',

        # Augmentation (light - we already augmented)
        hsv_h=0.015,                 # Hue
        hsv_s=0.3,                   # Saturation
        hsv_v=0.3,                   # Value
        degrees=5,                   # Small rotation (we did large rotations)
        translate=0.05,              # Small translation
        scale=0.1,                   # Small scale
        mosaic=0.3,                  # Light mosaic
        flipud=0.0,                  # No vertical flip (helipad has orientation)
        fliplr=0.5,                  # Horizontal flip OK

        # Training settings
        patience=20,                 # Early stopping patience
        save=True,
        plots=True,
        verbose=True,

        # Project organization
        project='results',
        name='helipad',
        exist_ok=True,
    )

    # Copy best model to models directory
    models_dir = Path('models')
    models_dir.mkdir(exist_ok=True)

    best_model = Path('results/helipad/weights/best.pt')
    if best_model.exists():
        import shutil
        dest = models_dir / 'best.pt'
        shutil.copy(best_model, dest)
        print(f"\nBest model saved to: {dest}")

        # Export to ONNX
        print("\nExporting to ONNX...")
        model = YOLO(str(dest))
        model.export(format='onnx', imgsz=args.imgsz)

        onnx_src = dest.with_suffix('.onnx')
        if onnx_src.exists():
            print(f"ONNX model saved to: {onnx_src}")

    print("\nTraining complete!")
    print("\nNext steps:")
    print("  1. Review results in results/helipad/")
    print("  2. Test: python test.py --image <test_image.jpg>")
    print("  3. Deploy models/best.onnx to your drone")


if __name__ == '__main__':
    main()
